### ISSUE TITLE
Data augmentation

### ISSUE THREAD

**Issue by SmoothJing** [Vanint/DatasetExpansion#6]
Hello seniors, can this data augmentation method be used in the field of speech.

**Comment by YifanZhang07** [comment]
Hello, our proposed method is specifically designed for image datasets, as models like Stable Diffusion are text-to-image generation models and CLIP serves as an image zero-shot classifier. Unfortunately, this means it cannot be directly applied to the speech domain. If you wish to use our approach in the speech domain, you will need to find a generator and a corresponding zero-shot classifier that are tailored for speech data.

**Comment by SmoothJing** [comment]
Ok, I get it. Thank you for your patience
